### ISSUE TITLE
Add option for remote repository URL

### ISSUE THREAD

**Issue by siwon** [orhun/git-cliff#112]
**Is your feature request related to a problem? Please describe.**
When I use conventionnal commit with `fix #issue_number`, the url generated by git-cliff is pointing git-cliff repository instead of my current remote repository url.

Example :
```md
### Features

- Use latest image orhunp/git-cliff ([#1](https://github.com/orhun/git-cliff/issues/1))
```

As you can see, the url is pointing to your repo instead of mine.

**Describe the solution you'd like**
Is it possible to add an option to specify the repo url I want to use ?
I know there is an option in the config file, but I think on option in the command line is better solution.

For example : 

```txt
  --remote_repo_url <url repo> : the remote url for issue refs.
```

**Describe alternatives you've considered**
I use git-cliff inside Gitlab-CI so I use a sed command on the result to replace your repo url with mine.

PS: thanks a lot for your work !

**Comment by FlrnFrmm** [comment]
Tried to implement the feature with #121

**Comment by FlrnFrmm** [comment]
Oh, and I realized I made a mistake.

I assumed (and I have honestly no clue how I got to that conclusion) that issue short links are `#i` and pull requests `@i`.
But now I've realized they are both just `#i`.
My problem is now, how to decide which reference is an issue and which is a pull request.
That is necessary because the routes differ: `../issues/{i}` vs. `../pull/{i}`.

One option would be to match against more than just `#i`, e.g.: 
- `#i` for issues
- `pr #i` | `pull request #i` | `Pull Request #i` for Pull Requests

Or is there a GitHub endpoint that redirects the `i` to the correct origin?

**Comment by FlrnFrmm** [comment]
Solved my problem, and realized I can use `../issues/{i}` for both.
GitHub redirects correctly to issues if `#i` is an issue and to PRs if it is a PR.

**Comment by orhun** [comment]
I had a look at this with fresh eyes and this is caused by the default config, as you mentioned:

https://github.com/orhun/git-cliff/blob/9a070b248d4ae0b58c9463f0627c87ca647c3023/config/cliff.toml#L39-L41

So you should be fine when you just change that line to point your own repository.

But still, it's annoying. So I pushed 8f77caf86a1e5dd23eda1b9e9b5a7a6606642b8a to comment this entry out.

So there is no need for overcomplicating this via #121. It is always good to refrain from adding code-hosting related things to `git-cliff` since it is not specifically designed to work with e.g. GitHub, GitLab, etc. These remote URLs might change any time depending on which platform you are using. `git-cliff` should only integrate well with `git` and it should be configurable based on user liking.

Hope this solves it! 🐻

**Comment by orhun** [comment]
You can now achieve this with the [GitHub integration](https://git-cliff.org/docs/integration/github).
