### ISSUE TITLE
Link PR and author by commits

### ISSUE THREAD

**Issue by medikoo** [orhun/git-cliff#12]
**Describe the solution you'd like**

I'd love to automate generation of Changelog that's presented on [serverless](https://github.com/serverless/serverless/releases) project, which: 

- By each commit links PR with which it was introduced
- By each commit presents author name and links it to author's GitHub profile
- Allow to group changes by scope

Is that possible with git-cliff?

**Comment by orhun** [comment]
> Is that possible with git-cliff?

Not really. `git-cliff` **only** uses git history and it is unaware of which hosting platform (GitHub, GitLab etc.) you are using. It is designed this way.

> * By each commit links PR with which it was introduced
> 
> * By each commit presents author name and links it to author's GitHub profile

These are not possible due to the reason I mentioned earlier. However, the [committer](https://docs.rs/git2/0.13.22/git2/struct.Commit.html#method.committer) and [author](https://docs.rs/git2/0.13.22/git2/struct.Commit.html#method.author) information can be added to the [context](https://github.com/orhun/git-cliff#context) in the future.

> * Allow to group changes by scope

This can be done by using the `scope` field in the template. See the [scoped example](https://github.com/orhun/git-cliff#scoped).

Also, I suggest checking out the [similar projects](https://github.com/orhun/git-cliff#similar-projects), there you might find a tool to meet your requirements.

**Comment by medikoo** [comment]
Thanks @orhun for clarifications.

Feel free to close the issue if it's _wontfix_.

**Comment by orhun** [comment]
You can now achieve this with the [GitHub integration](https://git-cliff.org/docs/integration/github).
