### ISSUE TITLE
Tag parser seem to remove all "v" from version tags by default

### ISSUE THREAD

**Issue by jabdoa2** [orhun/git-cliff#18]
**Describe the bug**
In the Mission Pinball Framework we tag our commits as `v0.56-dev.0` for development releases. Unfortunately, in `git cliff` those show up as `0.56-de.0` (notice the missing `v`).

Is there any guide how to change the tag regex? Standard perl syntax does not seem to work.

**To Reproduce**
1. Tag a commit as ``v0.56-dev.0`
2. Add some commits on top
3. Run `git cliff`

**Expected behavior**
I would like cliff to show `0.56-dev.0` in the headline instead of `0.56-de.0`.

**Screenshots/Logs**
```
## [0.56-de.0] - 2021-07-25
```

**Comment by orhun** [comment]
Good catch! It is fixed in e444615c02749da5fc64ae3286bfde1b616e7271. Default configuration removes only the leading "v" from the tag now.

This changes will be shipped with the upcoming release so feel free to try out and report bugs by either pulling the [docker image](https://hub.docker.com/layers/orhunp/git-cliff/sha-e444615/images/sha256-1eec5ad615183f4baae848ab62d68e5156aa64a21cd7f215277a625c26653261?context=repo) or [building from source](https://github.com/orhun/git-cliff#build-from-source).

**Comment by jabdoa2** [comment]
Thanks!

**Comment by orhun** [comment]
`v0.4.0` is released now.
