### ISSUE TITLE
Commits are missing when they have a body without blank line

### ISSUE THREAD

**Issue by sporto** [orhun/git-cliff#291]
**Describe the bug**

If I have a commit with with line like
```
fix: add something
```

or a commit with a blank line after the message:
```
fix: add something

Some description
```

They show in the changelog.

But I have a commit body without a blank line
```
fix: add something
Some description
```

They are not showing in the changelog.

**To reproduce**

Add a commit with the body. Without a blank line.

**Expected behavior**

All commits to show in changelog

**Screenshots / Logs**

**Software information**

- Operating system: MacOS 13.4
- Rust version: N/A
- Project version: 1.3

**Additional context**

Thanks

**Comment by alfonsocuccaro** [comment]
try adding `{ pattern = "\n", replace = " "}` in your `commit_preprocessors` in cliff.toml.

If you don't use other preprocessors, it should look like this

```
commit_preprocessors = [
    { pattern = "\n", replace = " "}
]
```

**Comment by sporto** [comment]
@alfonsocuccaro thanks, that is good workaround. The missing commits are now showing.

However this seems to be conflicting with `link_parsers`. After doing this, links appear twice in the changelog. E.g. we have a commit like:

```
feat: add something
https://stax.atlassian.net/browse/ABC-1234
```

In the changelog the link appears twice
```
- Add something https://stax.atlassian.net/browse/ABC-1234  [ABC-1234](https://stax.atlassian.net/browse/ABC-1234)
```

Link parser looks like
```
link_parsers = [
  { pattern = "https://stax.atlassian.net/browse/(\\w+)-(\\d+)", href = "https://stax.atlassian.net/browse/$1-$2", text="$1-$2"}
]
```

**Comment by orhun** [comment]
Hello! Sorry for the late reply.

Commits in the given format are not conventional according to the [conventional commits specification,](https://www.conventionalcommits.org/en/v1.0.0/). That's why the underlying library ([git-conventional](https://github.com/crate-ci/git-conventional)) is unable to parse them thus they do not appear in the changelog. (see the parser [here](https://github.com/crate-ci/git-conventional/blob/master/src/parser.rs).)

In order to have these commits in the changelog, simply disable conventional commits filter:

```toml
[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = false
```

Now they appear in the changelog as follows:

```md
### Bug Fixes

- Fix: add something
Some description
```

You can use `commit_parsers` to change the group/scope of the commit:

```toml
commit_parsers = [
  { message = "^fix", group = "Bug Fixes" },
]
```

Link parsers should also work as expected now.

I hope this helps! 🐻
