### ISSUE TITLE
Multiline commit messages not being fully captured

### ISSUE THREAD

**Issue by jinlow** [orhun/git-cliff#33]
**Describe the bug**
This might just be my misunderstanding of how to format conventional commits, but I am running into an issue where `git-cliff` is not picking up the full message of multiline commits. I would expect it to be able to include the full commit message in the changelog even if it has newlines present.

**To Reproduce**
1. Create a multiline commit message.
![image](https://user-images.githubusercontent.com/38221700/142292531-32d80f43-917f-49e0-b83c-6f7ba783ce90.png)
The full message appears in the gitlog.
![image](https://user-images.githubusercontent.com/38221700/142292603-d5a71b7c-106e-418a-874b-e8ae983b70e1.png)

2. However when I create the changelog, only the message up to the newline is present.
![image](https://user-images.githubusercontent.com/38221700/142292680-0b73aadf-69bd-4b56-81c3-fadaae972e05.png)

**Expected behavior**
 I would expect it to be able to include the full commit message in the changelog even if it has newlines present.

**System (please complete the following information):**
 - OS Information: Windows 10
 - Git-cliff version: 0.4.2

**Comment by orhun** [comment]
Hello! Thanks for reporting this.

This is related to the `git-conventional` crate which `git-cliff` heavily depends on for parsing. I created an issue there: 

- https://github.com/crate-ci/git-conventional/issues/19

**Comment by orhun** [comment]
It turns out that newlines in commit messages are not conventional: https://github.com/crate-ci/git-conventional/issues/19#issuecomment-974399723

Although simple workarounds can be applied for this case (e.g. escaping newlines before processing a commit or replacing newlines with whitespace), it is better to make `git-cliff` stick to the conventions. Thus I decided to take no action for this.

What I can suggest is basically use the commit description or footers, since they allow having multiline values. Also, maybe in the future, I can add a pre-processing mechanism for commit messages so that they can be manipulated before the parsing happens.
