### ISSUE TITLE
Print a message if a newer version of the CLI application is available

### ISSUE THREAD

**Issue by beardgans** [orhun/git-cliff#69]
Hi everyone and thank you so much for this wonderful project!

**Is your feature request related to a problem? Please describe.**
It would be nice to receive notification in the terminal if there is a new version of the CLI application.

**Describe the solution you'd like**
Show a message if a newer version of the CLI application is available.

**Describe alternatives you've considered**
I  found this useful feature in the GitHub [CLI application](https://cli.github.com/).

**Additional context**
I found 2 useful crates to do that:
* https://github.com/mgrachev/update-informer
* https://github.com/tarikeshaq/update-notifier

What do you think about it?

**Comment by orhun** [comment]
> What do you think about it?

I think it is a great idea!

I implemented this in 720a7c1ec2cde510733d119b7b3b8a938ff945ff using [update-informer](https://github.com/mgrachev/update-informer) library.

**Comment by orhun** [comment]
For anyone who is interested in why [720a7c1](https://github.com/orhun/git-cliff/commit/720a7c1ec2cde510733d119b7b3b8a938ff945ff) is failing, there is a regression in nightly Rust 😕:

- https://github.com/briansmith/ring/issues/1469
- https://github.com/rust-lang/rust/issues/95267

**Comment by beardgans** [comment]
Cool! Thanks!

I look forward to the release of the new version.

**Comment by alerque** [comment]
Can this please be hidden behind a features flag so that distro packages can disable it? I and many others have strong aversions to software that phones home for any reason. I don't want anything I do from the CLI to trigger network access unless specifically requested, and when software is updated in distro packages anyway these are usually false alarms.

**Comment by orhun** [comment]
> Can this please be hidden behind a features flag so that distro packages can disable it? I and many others have strong aversions to software that phones home for any reason. I don't want anything I do from the CLI to trigger network access unless specifically requested, and when software is updated in distro packages anyway these are usually false alarms.

Sure, it is now a part of `update-informer` feature (which is enabled by default). You can use `--no-default-features` flag for disabling it.

**Comment by alerque** [comment]
Great, thanks. Lets adjust the default features for the Arch package on the next release since that's one place the updater isn't that helpful. Having it enabled by default makes some sense as a reminder to the people that just did `cargo install`, but distro packages should probably all specifically disable it.

**Comment by orhun** [comment]
> Great, thanks. Lets adjust the default features for the Arch package on the next release since that's one place the updater isn't that helpful. Having it enabled by default makes some sense as a reminder to the people that just did `cargo install`, but distro packages should probably all specifically disable it.

Yup, I agree.
