### ISSUE TITLE
Configuration to set the sorting order of the sections

### ISSUE THREAD

**Issue by kaushalmodi** [orhun/git-cliff#78]
**Is your feature request related to a problem? Please describe.**

I see that right now the sections are getting organized lexicographically. I would like to order the sections so that the more important (subjective) ones like "Breaking", "Features" and "Bug Fixes" are at the top, and stuff like "Documentation" are at the bottom.

**Describe the solution you'd like**

Provide a `cliff.toml` variable where we can set the sort order like:

```toml
section_order = [ ":boom: Breaking", ":sparkles: Features", ":zap: Performance", ":bug: Bug Fixes", ":memo: Documentation", ":recycle: Refactor", ":hammer: Testing" ]
```

**Describe alternatives you've considered**

I am rendering the generated CHANGELOG to HTML so I am embedding a numeric order hidden in `display:none;` inline CSS styles.

```toml
  commit_parsers = [
      # https://www.conventionalcommits.org/en/v1.0.0/#summary
      { message = "!:"                                     , group = "@@html:<span style=\"display:none;\">0</span>@@ :boom: Breaking"},
      { message = "^feat"                                  , group = "@@html:<span style=\"display:none;\">1</span>@@ :sparkles: Features"},
      { message = "^perf"                                  , group = "@@html:<span style=\"display:none;\">2</span>@@ :zap: Performance"},
      { message = "^fix"                                   , group = "@@html:<span style=\"display:none;\">3</span>@@ :bug: Bug Fixes"},
      { message = "^docs?"                                 , group = "@@html:<span style=\"display:none;\">4</span>@@ :memo: Documentation"},
      { message = "^refactor"                              , group = "@@html:<span style=\"display:none;\">5</span>@@ :recycle: Refactor"},
      { message = "^test"                                  , group = "@@html:<span style=\"display:none;\">6</span>@@ :hammer: Testing"},
      { message = "^(chore.*|ci:)", skip = true},
      { body = "BREAKING CHANGE:"                          , group = "@@html:<span style=\"display:none;\">0</span>@@ :boom: Breaking"},
```

.. and it works! : https://ox-hugo.scripter.co/doc/changelog/#0-dot-9-dot-0

![image](https://user-images.githubusercontent.com/3578197/161674865-cccd8f03-bf75-443b-81c2-bac4aa171958.png)

But it would be reallly nice to get rid of all that HTML noise from `cliff.toml` and the generated `CHANGELOG.org` (oh, and yes, I am generating [this Org mode CHANGELOG.org](https://github.com/kaushalmodi/ox-hugo/blob/7af7e72e139655132cfa3ca5b9152690b8eaf1fe/CHANGELOG.org) instead of a Markdown thanks to the Tera templating support! 🙇‍♂️ )

https://github.com/kaushalmodi/ox-hugo/blob/7af7e72e139655132cfa3ca5b9152690b8eaf1fe/doc/cliff.toml#L60-L68

**Comment by orhun** [comment]
Hello!

This is related to #9, see [my comment](https://github.com/orhun/git-cliff/issues/9#issuecomment-914545201) there.

As I said, enabling `preserve_order` feature on `serde_json` makes the `group_by` filter preserve the commit order thus groups are ordered by their first appearance in the commit list. Instead of this, groups should be ordered manually by their defined order and this should also be done after grouping the commits via `group_by`:

```
commits | group_by(attribute="group")
```

The issue here is it is not possible to modify the result of Tera filters without defining a custom [`Filter`](https://docs.rs/tera/1.15.0/tera/trait.Filter.html). I could add a new filter named `ordered_group_by` but then it is not possible to pass the order (`section_order`) internally. In that case, it would look something like this which is not ideal I think:

```
commits | ordered_group_by(attribute="group", order = ...)
```

Another possible solution is to apply the lexicographic hack: modify the group prefix before rendering the template and remove it afterward. This is also not ideal 😕 

I will keep looking for different solutions to make it easier to provide a way for sorting the groups. I might have explained it in a complicated way so I can put it again with simpler words if that's the case 🙂 Also, I appreciate it if anyone wants to jump in and tackle this.

**Comment by kaushalmodi** [comment]
>This is related to https://github.com/orhun/git-cliff/issues/9

Oops! It looks like this is the exact same issue. Feel free to close this.

My search skills failed.. I was looking for "section order" and not "group order", and search for order showed results related to ordering the commits 😄 .

That issue uses an even better workaround.. to use `<!-- order # -->`. I will use that now on.

---

> Another possible solution is to apply the lexicographic hack: modify the group prefix before rendering the template and remove it afterward. This is also not ideal 😕

It's alright.. at least it works! 👍 

> Also, I appreciate it if anyone wants to jump in and tackle this.

Unfortunately, I couldn't as I haven't coded in Rust. I can help in any other way possible: Testing something, etc.
