### ISSUE TITLE
Missing optional scopes

### ISSUE THREAD

**Issue by stratosgear** [orhun/git-cliff#8]
**Is your feature request related to a problem? Please describe.**
I cannot iterate over commits that are missing a scope.

According to the Tera [docs](https://tera.netlify.app/docs/#group-by) of group-by, items that lack an attribute are discarded.

This means that if I want to have a scoped changelog, as per the git-cliff example, (and I **do**) then these commits are skipped from the changelog.

**Describe the solution you'd like**
I would like `git-cliff` to mark these commits in a specially named scope (maybe called `unscoped`? maybe have it configurable?) so I can iterate over them in my template and create a special section/heading for them

**Describe alternatives you've considered**
If git-cliff does not somehow mark these missing scopes, I do not believe there is an alternative on iterating over them.

**Additional context**
Some capture of the output of git-clif when scopes are missing:

```
# Changelog
All notable changes to this project will be documented in this file.

## [unreleased]

### Documentation

### Infrastructure

#### Ide

- Added git commit hooks for conventional messages
- Added suggested VS Code extensions

<!-- generated by git-cliff -->
```

Note the Documentation section that does **not** display any commits there (since the commit message is like `docs: some commit message`

**Comment by orhun** [comment]
Hello! Thanks for submitting this. It's implemented in b5df656.

I thought it'd be best to make this configurable via `commit_parsers` so that a "default" scope can be used for each group:

```toml
commit_parsers = [
    { message = "^feat*", group = "Features", default_scope = "general"},
    { message = "^fix*", group = "Bug Fixes", default_scope = "other"},
    { message = "^doc*", group = "Documentation", default_scope = "unscoped"},
]
```

`default_scope` will be used if there's no "conventional scope" (in other words: if it's missing). So when you use the config values from above with the following git history:

```
* docs(config): support multiple file formats
* docs: some commit message
```

You get the following:

```md
### Documentation

#### Config

- Document values

#### Unscoped

- Some commit message
```

I think this meets your requirements 😃 

`default_scope` will be available with the next release but feel free to try it out now and report bugs if any.

**Comment by stratosgear** [comment]
Sure, that would do fine! 

Now, all I need is a new release so I can pull the new version in my build image so I can continue automating things.  Sagol! :)

**Comment by orhun** [comment]
`v0.3.0` is released.
