### ISSUE TITLE
`--from-context` doesn't include footers

### ISSUE THREAD

**Issue by muja** [orhun/git-cliff#837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

```
 ERROR git_cliff > Template render error:
Variable `commit.footers` not found in context while rendering 'template'
```

### Steps To Reproduce

You can test with my repository's template at https://github.com/muja/unrar.rs, for example where I use footers.

`git cliff --context` gives `footers`, however

`git cliff --context | git cliff --context --from-context -` has no footers.

### Expected behavior

`footers` are read from context

### Software information

- Project version: 2.5.0

### Additional context

Possibly other values are also missing? I haven't fully compared the contexts

**Comment by orhun** [comment]
Good find! This is due to `footers` being serialized manually:

https://github.com/orhun/git-cliff/blob/08e761c20fb98730249aef2047da02a7dfca86ad/git-cliff-core/src/commit.rs#L427

https://github.com/orhun/git-cliff/blob/08e761c20fb98730249aef2047da02a7dfca86ad/git-cliff-core/src/commit.rs#L405-L419

We simply need to add a `Vec<Footer>` field to `Commit` for enabling the deserialization.

I might get to it soon, marking it as good first issue in case someone wants to work on it :)

**Comment by muja** [comment]
FYI I compared the diffs between `git cliff --context` and `git cliff --context | git cliff --context --from-context -`. These are the differences:

1. missing fields: `footers`, `body`, `breaking_description`, `breaking`
2. `conventional` flipped from `true` to `false`

**Comment by orhun** [comment]
Thanks for the comparison! It will definitely come in handy while working on the fix.

**Comment by dqkqd** [comment]
@orhun 
Hi, I'm trying to fix this issue. Surely, adding `footers` into `Commit` is an easy fix for this.

But as @muja mentioned above, `body`, `breaking`, and some other fields were missing during reading and writing context. I think a proper fix should address them as well.

Looking at the serialization code, I found that we are trying to convert some fields from `conv` into `Commit`. For example, assigning `message` from `conv` to `Commit`, and since they are not identical, we lose data after converting to `context`.

Maybe we should retain some information so that after writing to `context`, we can read it back without any loss of data.
`message` should be the good one, since we can create `conv` from it. Or we can add another field (e.g `raw_message`) ?
https://github.com/orhun/git-cliff/blob/08e761c20fb98730249aef2047da02a7dfca86ad/git-cliff-core/src/commit.rs#L221-L224

What do you think?

**Comment by orhun** [comment]
Hey @dqkqd, that sounds reasonable 👍🏼 I'm looking at your PR right now :) Thanks
