### ISSUE TITLE
[Question] Use git-cliff to validate commit messages

### ISSUE THREAD

**Issue by alexanderwe** [orhun/git-cliff#88]
Hey, at first thanks a lot for this nice tool ! I have a question though. Is it possible to use `git-cliff` and its configuration file to validate that a commit message is a valid one ? 

The use case would be, to use it in a pre-commit hook to ensure that the commit that is about to be made matches the `git-cliff` configuration ? So something like a validation mode for a single commit message.

**Comment by orhun** [comment]
Hello!

 [cocogitto](https://github.com/cocogitto/cocogitto) is the tool that you are looking for, I won't be implementing this feature for `git-cliff`.

Thanks for the suggestion 🐻

**Comment by alexanderwe** [comment]
@orhun Thanks a lot for the tool suggestion and answering my question !

**Comment by c0dearm** [comment]
Hi @orhun! Sorry to re-open this conversation again. I was wondering what's the justification for this decision. This tool already needs to parse the commit history to be able to extract the changelog content, so it seems it should be pretty straightforward to have a "--check" flag or something similar that just exits with an error exit code if a given range of commit lints does not conform to the standard.

I think it would be quite beneficial for those users that want to integrate this tool into their CI/CD pipelines, because in one end you would like all your commits to fulfill the standard and on the other hand you would like to generate a changelog at some point. If the same image can be re-used there's less software to maintain.

Thanks for this tool! :heart:
