### ISSUE TITLE
link_parsers don't generate links

### ISSUE THREAD

**Issue by lewisboon** [orhun/git-cliff#93]
**Describe the bug**

link_parsers don't generate links.

**To Reproduce**

1. Clone this repository
2. Copy the `config/cliff.toml` file to the repository root
3. Run `git cliff --latest`. The `commit_preprocessors` will convert issues to links.
4. Remove the `commit_preprocessors` config and add (sourced from the README.md):
```toml
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/orhun/git-cliff/issues/$1"},
]
```
5. Run `git cliff --latest`. Links will not be rendered.

**Expected behavior**
The regex pattern of the `link_parsers` should be honoured.

**Screenshots/Logs**

**System (please complete the following information):**
 - OS Information: Ubuntu 20.04
 - Project Version: 0.7.0

**Comment by orhun** [comment]
In order to use the links parsed by `link_parsers`, you need to update your changelog template. It does not work the same as `commit_preprocessors`, it is only for extracting the links, not for replacing the given regex with them.

As stated in [README.md](https://github.com/orhun/git-cliff#context), you can use the `links` fields from the context:

```json
"commits": [
    {
      "id": "e795460c9bb7275294d1fa53a9d73258fb51eb10",
      "message": "<description>",
      "..."
      "links": [{"text": "(set by link_parsers)", "href": "(set by link_parsers)"}]
    }
  ]
```

An example would be:

```toml
[changelog]
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}\
        {%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}){% endfor -%}){% endif %}\
    {% endfor %}
{% endfor %}\n
"""

[git]
link_parsers = [
    { pattern = "#(\\d+)", href = "https://github.com/orhun/git-cliff/issues/$1"},
]
```

Pay attention to this line:

```
{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}){% endfor -%}){% endif %}\
```

This will result in:

```md
## [0.6.0] - 2022-02-12

### Bug Fixes

- Only drop previous releases if skipped (#44) ([#44](https://github.com/orhun/git-cliff/issues/44))
```

I think you were expecting `link_parsers` to do something different. Let me know if there is another thing that I can help you with! 🐻
